// src/lib/dummyData.js
// Dummy data — exact field names from CSV sheets
// lead_type: 'ucc' | 'trigger' | 'aged' | 'web' | 'live_transfer'
// Replaced with Supabase fetch in Phase 2

export const dummyLeads = [
  {
    id: 1,
    lead_type: "ucc",
    lead_vendor: "UCC Direct",
    first_name: "David",
    last_name: "Perkins",
    company_name: "Reelfoot Enterprises",
    phone: "+17314429272",
    state: "TN",
    status: "New",
    lead_score: 80,
    name: "David Perkins",
    number_type: "Mobile",
    title: "PRINCIPAL",
    email: "dwperkins2000@hotmail.com",
    address: "123 Main St",
    city: "Memphis",
    zip: "38101",
    sic_code: "15220000.0",
    sic_description: "RSDNTL CNSTR NEC",
    employee_size: 3,
    revenue: 81400,
    filing_day: 11,
    filing_month: 3,
    filing_year: 2026,
    sec_partyname: "INDL TRUCKS TRCTOR",
  },
  {
    id: 2,
    lead_type: "ucc",
    lead_vendor: "UCC Direct",
    first_name: "DOMONIC",
    last_name: "WRIGHT",
    company_name: "WRIGHT ENTERPRISES LV LLC",
    phone: "+17026891745",
    state: "NV",
    status: "Contacted",
    lead_score: 72,
    name: "DOMONIC WRIGHT",
    number_type: "Mobile",
    title: "OWNER",
    email: "dwright1689@gmail.com",
    address: "5883 BRIGHT ROSE DR",
    city: "LAS VEGAS",
    zip: "89122",
    sic_code: "75320401.0",
    sic_description: "Body Shop, Automotive",
    employee_size: 0,
    revenue: 250000,
    filing_day: 30,
    filing_month: 3,
    filing_year: 2026,
    sec_partyname: "WOMENS CLOTHNG STRS",
  },
  {
    id: 3,
    lead_type: "trigger",
    lead_vendor: "Trigger Data Co",
    first_name: "ETHEL",
    last_name: "POLLARD",
    company_name: "LITTLE LEARNERS PHASE II",
    phone: "+18133256371",
    state: "FL",
    status: "New",
    lead_score: 65,
    name: "ETHEL POLLARD",
    number_type: "Mobile",
    title: "PRINCIPAL",
    email: "ejones3535@yahoo.com",
    sic_code: "59920000.0",
    sic_description: "FLORISTS",
    day: 3,
    month: 3,
    year: 2026,
  },
  {
    id: 4,
    lead_type: "trigger",
    lead_vendor: "Trigger Data Co",
    first_name: "Jennifer",
    last_name: "Feim",
    company_name: "EJ'S 1 LLC",
    phone: "+19046547600",
    state: "FL",
    status: "Callback",
    lead_score: 60,
    name: "Jennifer Feim",
    number_type: "Mobile",
    title: "OWNER",
    email: "ejspizza7437918@gmail.com",
    sic_code: "57120102.0",
    sic_description: "Mattresses",
    day: 9,
    month: 3,
    year: 2026,
  },
  {
    id: 5,
    lead_type: "aged",
    lead_vendor: "Aged List Pros",
    first_name: "Alexandra",
    last_name: "Champ",
    company_name: "Learn2lax LLC",
    phone: "+12012666039",
    state: "NJ",
    status: "New",
    lead_score: 30,
    name: "Alexandra Champ",
    email: "info@learn2lax.com",
    line_type: "Landline",
  },
  {
    id: 6,
    lead_type: "aged",
    lead_vendor: "Aged List Pros",
    first_name: "Ronald",
    last_name: "Williams",
    company_name: "Brasserie",
    phone: "+12012666400",
    state: "NJ",
    status: "Not Interested",
    lead_score: 20,
    name: "Ronald Williams",
    email: "rcwii@yahoo.com",
    line_type: "Landline",
  },
  {
    id: 7,
    lead_type: "web",
    lead_vendor: "Web Funnels Inc",
    first_name: "Trent",
    last_name: "Gaites",
    company_name: "Sport Worx",
    phone: "+16785416810",
    state: "GA",
    status: "App Sent",
    lead_score: 90,
    name: "Trent Gaites",
    email: "tg@sportworx.com",
    requested_amount: "$15,000.00",
    why_funds: "Working Capital",
    tib: "28 Years",
    monthly_deposit: "$30,000.00",
    best_time: "3:00 PM EST",
    fico: 550,
    lead_type_label: "Web Leads (1-7 Days)",
    date_sold: "4/27/2026",
  },
  {
    id: 8,
    lead_type: "web",
    lead_vendor: "Web Funnels Inc",
    first_name: "Sylvia",
    last_name: "Busby",
    company_name: "Loving Care Incorporated",
    phone: "+12533890068",
    state: "WA",
    status: "New",
    lead_score: 88,
    name: "Sylvia Busby",
    email: "silviadusby@yahoo.com",
    requested_amount: "$100,000.00",
    why_funds: "Expansion",
    tib: "16 Years",
    monthly_deposit: "$25,000.00",
    best_time: "6:00 PM ET",
    fico: 720,
    lead_type_label: "Web Leads (1-7 Days)",
    date_sold: "4/27/2026",
  },
  {
    id: 9,
    lead_type: "live_transfer",
    lead_vendor: "Live Transfer Pro",
    first_name: "Marcus",
    last_name: "Johnson",
    company_name: "Johnson Auto Detail",
    phone: "+13055551234",
    state: "FL",
    status: "New",
    lead_score: 95,
    name: "Marcus Johnson",
    email: "marcus@johnsondetail.com",
    requested_amount: "$25,000.00",
    why_funds: "Equipment",
    tib: "5 Years",
    monthly_deposit: "$18,000.00",
    best_time: "Now",
    fico: 640,
    lead_type_label: "Live Transfer",
    date_sold: "4/29/2026",
  },
];
