ALTER TABLE application_requests
  ADD COLUMN IF NOT EXISTS phone           TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS dba             TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS business_address TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS owner_address   TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ein             TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS time_in_business TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS dob             TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ssn             TEXT NOT NULL DEFAULT '';
